### ISSUE TITLE
what's your favorite/most-effective learning method?

### ISSUE THREAD

**Issue by ahmadnassri** [blainsmith/ama#15]

**Comment by blainsmith** [comment]
Learning by doing works best for me, however, I do spend a lot of time reading at the very beginning to understand the basic concepts. This way I have a good foundation before I dive in. 

The hard part of "doing" is deciding on a conceptual model to work with. You can only write a blog system so many times in so many languages before it gets boring. That is why I co-started http://agnostechvalley.com to give others the chance to come learn and do after given a quick 10-minute lesson on whats going to be used. Mini conference + hack session in just a few hours.
