### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [blainsmith/ama#6]

**Comment by blainsmith** [comment]
Oh wow, this is a really hard choice. Ones that really got me to laugh out loud were...

![cosby](http://31.media.tumblr.com/fc482e078a32c888f135bc1ef46ed89e/tumblr_mtfioaw3GL1s5e5bko2_500.gif)

![uw](http://ultimatewarrior.co/images/5.gif)

I loved Ultimate Warrior so much I had to get a site up for him too. http://ultimatewarrior.co
